---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Data visualization focussed story telling

<!-- badges: start -->
<!-- badges: end -->


## Story 1: Understanding the state of global air quality data, research and funding infrastructure


### Part 1: How much longer can you live if you breathed clean air and how does it compare with other health threats? - Air Quality Life Index

```{r echo=TRUE part1fig1}

# load in the aqli helper script (from the R/ subfolder of the repo) and download all relevant datasets as specified in the readme file of the repo.

# Define the target projection (Equal Earth - EPSG:8857)
equal_earth_proj <- "+proj=eqearth +datum=WGS84 +wktext"

# converting AQLI shapefiles to a Equal Earth Projection
gadm2_aqli_2021_shp <- st_transform(gadm2_aqli_2021_shp, equal_earth_proj)
gadm1_aqli_2021_shp <- st_transform(gadm1_aqli_2021_shp, equal_earth_proj)
gadm0_aqli_2021_shp <- st_transform(gadm0_aqli_2021_shp, equal_earth_proj)

# figuring out the objectids for gadm1 for which population is not available
obid_gadm1_pop_na <- gadm1_aqli_2021 %>% 
  filter(is.na(population)) %>%
  select(objectid_gadm1) %>% 
  unlist() %>%
  as.vector()

# figuring out the objectids for gadm0 for which population is not available
obid_gadm0_pop_na <- gadm0_aqli_2021 %>% 
  filter(is.na(population)) %>%
  select(objectid_gadm0) %>%
  unlist() %>%
  as.vector()


# global shapefile gadm2 map data
aqli_global_gadm2_data <- gadm2_aqli_2021 %>%
  left_join(gadm2_aqli_2021_shp, by = c("objectid_gadm2" = "obidgadm2")) %>%
  add_aqli_color_scale_buckets("lyl", "llpp_who_2021") %>%
  select(-geometry, geometry) %>%
  st_as_sf()

## removing extremely tiny polygons from all three shapefiles to focus on the main map

aqli_global_gadm2_data$area <- st_area(aqli_global_gadm2_data)

# minimum area threshold for the polygons
threshold <- 10000000 # units are m^2

# adding a "area without units" column
aqli_global_gadm2_data <- aqli_global_gadm2_data %>% 
  mutate(area_without_units = as.numeric(str_remove(area, " [m^2]"))) 

aqli_global_gadm2_data <- aqli_global_gadm2_data %>%
  filter(area_without_units > threshold) 

# filter out small island regions from all gadm shapefiles
aqli_global_gadm2_data <- aqli_global_gadm2_data %>%
  filter(country %notin% c("Samoa", "American Samoa", "French Polynesia", "Fiji", 
                           "Tonga", "Niue", "Cook Islands", "Vanuatu", "Solomon Islands", 
                           "Vanuatu", "New Caledonia", "Marshall Islands", "Micronesia", 
                           "French Southern Territories", "Saint Helena, Ascension and Tris")) %>%
  filter(!((country  == "New Zealand") & (name_1 == "Galápagos"))) %>%
  filter(!((country  == "United States") & (name_1 == "Hawaii"))) %>%
  filter(!is.na(population)) 

gadm1_aqli_2021_shp <- gadm1_aqli_2021_shp %>%
  filter(name0 %notin% c("Samoa", "American Samoa", "French Polynesia", "Fiji", 
                           "Tonga", "Niue", "Cook Islands", "Vanuatu", "Solomon Islands", 
                           "Vanuatu", "New Caledonia", "Marshall Islands", "Micronesia", 
                           "French Southern Territories", "Saint Helena, Ascension and Tris")) %>%
  filter(!((name0  == "New Zealand") & (name1 == "Galápagos"))) %>%
  filter(!((name0  == "United States") & (name1 == "Hawaii"))) %>%
  filter(obidgadm1 %notin% obid_gadm1_pop_na) 

gadm0_aqli_2021_shp <- gadm0_aqli_2021_shp %>%
  filter(name0 %notin% c("Samoa", "American Samoa", "French Polynesia", "Fiji", 
                           "Tonga", "Niue", "Cook Islands", "Vanuatu", "Solomon Islands", 
                           "Vanuatu", "New Caledonia", "Marshall Islands", "Micronesia", 
                           "French Southern Territories", "Saint Helena, Ascension and Tris")) %>%
  filter(obidgadm0 %notin% obid_gadm0_pop_na) 


# creating a tibble for text boxes annotation positions and labels in order: LA, Delhi, Ouest(Cameroon), Melbourne (Australia), Lima (Peru), Warsaw (Poland)
tb_annotation <- tibble(
  label_x = c(-139, 64.83, -9, 126.5, -87.72, -29.66),
  label_y = c(18.11, 7.5, -0.54, -49.09, -20.34, 40.04),
  text = c("**Los Angeles (US)**, 0.65 years = 7.8 months",
           "**Delhi (India)**, 11.9 years", 
           "**Ouest (Cameroon)**, 4.5 years", 
            "**Melbourne (Australia)** is in compliance with the WHO PM₂.₅ guideline of 5 µg/m³", 
            "**Lima (Peru)**, 2.3 years", 
            "**Warsaw (Poland)**, 1.2 years"))


# global AQLI map for explained.media website
aqli_global_gadm2_map <- aqli_global_gadm2_data %>%
  filter(continent == "Africa") %>%
  ggplot() +
  geom_sf(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), color = "transparent", lwd = 0) +
   geom_sf(data = gadm1_aqli_2021_shp %>% filter(continent == "Africa"), color = "transparent", fill = "transparent", lwd = 0) +
 geom_sf(data = gadm0_aqli_2021_shp %>% filter(continent == "Africa"), color = "aliceblue", fill = "transparent", lwd = 0.3) +
   scale_fill_manual(values = c("0 to < 0.1" = "#ffffff", 
                               "0.1 to < 0.5" = "#ffeda0", 
                               "0.5 to < 1" = "#fed976", 
                               "1 to < 2" = "#feb24c", 
                               "2 to < 3" = "#fd8d3c", 
                               "3 to < 4" = "#fc4e2a", 
                               "4 to < 5" = "#e31a1c", 
                               "5 to < 6" = "#bd0026", 
                               ">= 6" = "#800026")) +
    geom_textbox(data = tb_annotation, aes(x = label_x, y = label_y, label = text),
               colour = "white",
               box.colour = "#022531",
               fill = NA,
               family = "Segoe UI",
               size = 6.5) +
    #geom_curve(x = -118.25, xend = -134, y = 34.09, yend = 23.2, color = "white", arrow = arrow(), curvature = 0.5) +
 annotate("segment", x = -118.25, xend = -134, y = 34.09, yend = 23.2, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white") + # US
 annotate("segment", x = 77.14, xend = 65.09, y = 28.68, yend = 11.82, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white") +
 annotate("curve", x = 10.18, xend = -12.28, y = 5.5, yend = -20.96, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white", curvature  = -0.5) +
 annotate("segment", x = 144.97, xend = 131.18, y = -37.97, yend = -41.01, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white") +
 annotate("segment", x = -77.03, xend = -82.74, y = -12.02, yend = -16.39, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white") +
annotate("segment", x = 21.03, xend = -19.7, y = 52.24, yend = 43, arrow = arrow(type = "closed", length = unit(0.2, "inches")), colour = "white") +
      coord_sf(default_crs = sf::st_crs(4326)) +
  ggthemes::theme_map() +
labs(title = "How much longer can you live if you breathed clean air?",
     subtitle = expression("Life expectancy gains, if 2021" ~ PM[2.5] ~ "pollution is reduced to meet the WHO" ~ PM[2.5] ~ "guideline"),
     fill = "Potential gain in life expectancy (years)",
caption = expression("Source · Air Quality Life Index, Annual Report 2023 | Graphic · explained.media")) + 
  theme(legend.position = c(0.6, 0.98), 
        legend.background = element_rect(fill = "#022531"), 
        legend.text = element_text(color = "white", face = "bold" , size = 21), 
        plot.background = element_rect(colour = "#022531",
                                       fill = "#022531"), 
        plot.caption = element_text(size = 15, hjust = 0.5, color = "white"), 
        plot.title = element_text(size = 35, family = "Segoe UI", face = "bold", color = "white", hjust = 0.03, 
                                  margin = margin(b = 0.5, unit = "cm")),
        plot.subtitle = element_text(size = 22, family = "Segoe UI", face = "italic", color = "white", hjust = 0.03, 
                                     margin = margin(b = 0.5, unit = "cm")),
        legend.spacing.x = unit(1.5, "lines"), 
        legend.title = element_text(color = "white", hjust = 0.5, size = 25, family = "Segoe UI")) +
       # legend.margin = margin(b = 1, unit = "cm")) +
guides(fill = guide_legend(
    keywidth = unit(2, "lines"),  # Adjust key width
    keyheight = unit(2, "lines"),  # Adjust key height
    label.position = "bottom",  # Position labels below keys
    label.hjust = 0.5,  # Center labels horizontally
    label.vjust = 1,  # Adjust vertical positioning of labels
    nrow = 1, 
    shape = guide_legend(override.aes = list(shape = 19))
  )) 


# save plot
ggsave(paste0(here(), "/output/aqli_intro_map_linkedin.png"), aqli_global_gadm2_map, width = 17, height = 9, dpi = 320, scale = 2)

  



## Part 1 fig 2: Comparing PM2.5 with other health threats-----------------------------------------------------


# create a version of the figure with the same diseases as used in the same figure in last year's report
 
pm2.5_comparison_oth_threats_data <- gbd_results_master_2021 %>%
  filter(country == "Global", cause_of_death %in% c("PM2.5 relative to WHO guideline", "Tobacco", "Alcohol use", 
                                                    "Unsafe water, sanitation, and handwashing", 
                                                    "Transport injuries", 
                                                    "HIV/AIDS and sexually transmitted infections", 
                                                    "Neglected tropical diseases and malaria", 
                                                    "Nutritional deficiencies", 
                                                    "Child and maternal malnutrition"))
colnames(pm2.5_comparison_oth_threats_data)[3] <- c("llpp_who_2021")

pm2.5_comparison_oth_threats_data <- pm2.5_comparison_oth_threats_data %>%
    mutate(lyl_bucket = ifelse((llpp_who_2021 >= 0) & (llpp_who_2021 < 0.1), "0 - < 0.1", NA), 
         lyl_bucket = ifelse((llpp_who_2021 >= 0.1) & (llpp_who_2021 <= 0.5), "0.1 - 0.5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 0.5) & (llpp_who_2021 <= 1), "> 0.5 - 1", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 1) & (llpp_who_2021 <= 2), "> 1 - 2", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 2) & (llpp_who_2021 <= 3), "> 2 - 3", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 3) & (llpp_who_2021 <= 4), "> 3 - 4", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 4) & (llpp_who_2021 <= 5), "> 4 - 5", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 > 5) & (llpp_who_2021 < 6), "> 5 - < 6", lyl_bucket), 
         lyl_bucket = ifelse((llpp_who_2021 >= 6), ">= 6", lyl_bucket)) %>%
  mutate(order_lyl_bucket = ifelse(lyl_bucket == "0 - < 0.1", 1, NA), 
         order_lyl_bucket = ifelse(lyl_bucket == "0.1 - 0.5", 2, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 0.5 - 1", 3, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 1 - 2", 4, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 2 - 3", 5, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 3 - 4", 6, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 4 - 5", 7, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == "> 5 - 6", 8, order_lyl_bucket), 
         order_lyl_bucket = ifelse(lyl_bucket == ">= 6", 9, order_lyl_bucket))





# pm2.5 compared to other health threats plot

f1 <- "Rubik"

pm2.5_comparison_oth_threats_plt <- pm2.5_comparison_oth_threats_data %>%
  mutate(llpp_who_2021 = round(llpp_who_2021, 1), 
         cause_of_death = ifelse(cause_of_death == "PM2.5 relative to WHO guideline", "PM₂.₅ relative to WHO guideline", cause_of_death)) %>%
  ggplot(mapping = aes(x = forcats::fct_reorder(cause_of_death, llpp_who_2021), y = llpp_who_2021)) + 
  geom_blank() +
  #     annotate("segment", y = c(0.25, 0.75, 1.25), yend = c(0.25, 0.75, 1.25), x = 0, xend = 9,
  # colour = "#0C475F") +
# geom_hline(mapping = aes(yintercept = 0.25), color = "#0C475F", linetype = "solid") +
#   geom_hline(mapping = aes(yintercept = 0.75), color = "#0C475F", linetype = "solid") +
#   geom_hline(mapping = aes(yintercept = 1.25), color = "#0C475F", linetype = "solid") +
  geom_col(mapping = aes(fill = forcats::fct_reorder(lyl_bucket, order_lyl_bucket)), width = 0.4, color = "white") +
  geom_text(aes(label = llpp_who_2021, y = (llpp_who_2021 - 0.085)), hjust = -0.2, color = "#663300", size = 10, family = f1, 
            fontface = "bold") +
  labs(x = "", y = "Life years lost", fill = "Life years lost", 
       title = expression("How does" ~ PM[2.5] ~ "compare with other heath threats?"), 
       caption = "Sources · Air Quality Life Index, Annual Report 2023; Global Burden of Disease; WHO life tables | Graphic · explained.media") +
  coord_flip() + 
  ggthemes::theme_tufte() +
  scale_y_continuous(breaks = seq(0, 3, 0.5), limits = c(0, 2.5)) +
 # scale_x_discrete(limits = cause_of_death_ordered[seq(1, length(cause_of_death_ordered), by = 2)]) +
  scale_fill_manual(values = c("0 - < 0.1" = "#FFFFFF", 
                               "0.1 - 0.5" = "#FFE6B3", 
                               "> 0.5 - 1" = "#FFD25D", 
                               "> 1 - 2" = "#FFBA00", 
                               "> 2 - 3" = "#FF9600", 
                               "> 3 - 4" = "#FF6908", 
                               "> 4 - 5" = "#E63D23", 
                               "> 5 - < 6" = "#BD251C", 
                               ">= 6" = "#8C130E")) + 
   theme(legend.position = "none", 
        legend.background = element_rect(fill = "#022531"), 
        legend.text = element_text(color = "white", face = "bold" , size = 9),
        plot.background = element_rect(colour = "#022531",
                                       fill = "#022531"), 
        plot.caption = element_text(size = 12, hjust = 0.5, color = "white"), 
        plot.title = element_text(size = 20, family = "Segoe UI", face = "bold", color = "white", hjust = -3.3, 
                                  margin = margin(b = 0, unit = "cm")),
        plot.subtitle = element_text(size = 11, family = "Segoe UI", face = "italic", color = "white", hjust = 0, 
                                     margin = margin(b = 0.5, unit = "cm")),
        legend.spacing.x = unit(1.5, "lines"), 
        legend.title = element_text(color = "white", hjust = 0.5, size = 15, family = "Segoe UI"), 
        axis.text.y = element_text(color = c("PM₂.₅ relative to WHO guideline" = "#FFFFFF", 
                                             "Tobacco" = "#FFE6B3", 
                                             "Child and maternal malnutrition" = "#FFE6B3", 
                                             "Alcohol use" = "#FFE6B3", 
                                             "Unsafe water, sanitation, and handwashing" = "#FFD25D", 
                                             "Transport injuries" = "#FFD25D", 
                                             "HIV/AIDS and sexually transmitted infections" = "#FFBA00", 
                                             "Neglected tropical diseases and malaria" = "#FF9600", 
                                             "Nutritional deficiencies" = "#FF9600"), hjust = 0.5, size = 20, family = f1),
        axis.text.x = element_text(color = "white", hjust = 0.5, size = 20, family = f1),
        axis.title.x = element_text(color = "white", hjust = 0.99, size = 21, family = f1, margin = margin(b = 0.5, t = 0.2, unit = "cm")),
        axis.line = element_line(color = "#0C475F")) +
      ggtext::geom_textbox(aes(x = 4.9,
                             y = 1.3),
                         label = "How does the threat from **<span style=\"color:#CC6633\">particle pollution</span>** compare with other global health threats?",
                         hjust = -0.005, halign = 0,
                         vjust = 1, valign = 1,
                         family = f1,
                         lineheight = 0.35,
                         width = unit(55, "lines"),
                         size = 15,
                         box.colour = NA,
                         fill = NA,
                         color = "white") 
# save plot
ggsave(paste0(here(), "/output/linked_in_pm2.5_compared_to_other_threats.png"), pm2.5_comparison_oth_threats_plt, width = 11, height = 8, dpi = 320, scale = 2)


```

# experiment
```{r}

# cartogram US state level-------------------------

africa_countries <- gadm0_aqli_2021 %>% 
  filter(continent == "Africa") %>%
  select(country) %>%
  as.vector() %>%
  unlist()

# US state level shapefile
map_data <- gadm0_aqli_2021_shp %>%
  filter(name0 %in% africa_countries) %>%
  left_join(gadm0_aqli_2021 %>% filter(country %in% africa_countries), by = c("name0" = "country")) %>%
  select(name0, population, pm2021, llpp_who_2021, llpp_nat_2021, geometry) %>%
  mutate(pm2021 = pm2021*1000) %>%
  st_as_sf() 

map_data <- st_transform(map_data, crs = 7755)

map_data$name1 <- as.factor(map_data$name1)
map_data$pm2021 <- as.factor(map_data$pm2021)
plt <- cartogram_cont(map_data, "pm2021")

# json data ---------------------------------------

#jsonlite geojsonio geojsonsf
library(geojsonsf)
install.packages("rjson")

json_data_raw <- jsonlite::read_json("./id_1.json")

# b1
class(json_data_raw) # list
json_data <- jsonlite::toJSON(json_data_raw)

json_data_pretty <- jsonify::pretty_json(json_data)


tmp <-geojson::as.geojson(json_data)
class(tmp)
geojsonio::geojson_write(tmp, "test4.geojson", geometry = "polygon", group = group)

geojson_sf <- geojsonsf::geojson_sf(tmp)

geojson_data <- geojsonio::geojson_read("myfile.geojson")


tmp <- geojsonio::geojson_read("./gadm2.json")
tmp_json <- jsonlite::toJSON(tmp)
tmp1 <- geojsonio::geojson_json(tmp_json)










jsonlite::write_json(x = json_data, path = "./id_1_updated.json")
geojson_data <- geojsonio::file_to_geojson("id_1_updated.json", method = "local")

# b2

json_data_raw_df <- as.data.frame(tmp)

# Create a simple feature with the geometry and data
sf_feature <- st_sf(
  geometry = st_sfc(st_as_text(json_data_raw$feature$geometry)),
  data = data
)

gm <- st_as_sf(json_data_raw$feature$geometry)

x <- gsub("\n", "", paste0('https://gist.githubusercontent.com/hunterowens/25ea24e198c80c9fbcc7/raw/7fd3efda9009f902b5a991a506cea52db19ba143/wards2014.json', collapse = ""))


```



```{r}

epic_ind_df <- tibble(channel = c("Twitter", "Twitter", "LinkedIn", "LinkedIn"), month_year = c("June 2023", "Sept 2023", "June 2023", "Sept 2023"), followers =  c(2903, 2970, 7200, 8790))


epic_ind_df %>%
  ggplot(mapping = aes(x = month_year, y = followers)) +
  geom_line(mapping = aes(color =  channel, group = channel), lwd = 1) +
  scale_color_viridis(discrete = TRUE) +
  labs(x = "Month/Year", y = "Followers", color = "", title = "EPIC India 3rd quarter follower growth") +
  scale_y_continuous(breaks = seq(0, 9000, 1000), limits = c(0, 9000)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_text(hjust = 1, margin = margin(t = 0.5, unit = "cm")), 
        axis.title.y = element_text(hjust = 0.5, margin = margin(r = 0.5, unit = "cm")), 
        legend.position = "bottom", 
        plot.title = element_text(margin = margin(b = 0.5, unit = "cm"))) +
  geom_text(mapping = aes(label = followers), size = 4, hjust = 1, vjust = 0.01)

img <- epic_ind_df %>%
  ggplot(mapping = aes(x = channel, y = followers)) +
  geom_col(mapping = aes(fill =  month_year, group = month_year), position = "dodge", width = 0.5) +
  scale_fill_viridis(discrete = TRUE) +
  labs(x = "Channel", y = "Followers", fill = "", title = "EPIC India 3rd quarter follower growth") +
  scale_y_continuous(breaks = seq(0, 9000, 1000), limits = c(0, 9000)) +
  ggthemes::theme_clean() +
  theme(axis.title.x = element_text(hjust = 1, margin = margin(t = 0.5, unit = "cm")), 
        axis.title.y = element_text(hjust = 0.5, margin = margin(r = 0.5, unit = "cm")), 
        legend.position = "bottom", 
        plot.title = element_text(margin = margin(b = 0.5, unit = "cm"))) 

```
